Feature/issue 231 combine readme and runbook
galatea-associates/fuse-test-data-gen pull request #232
Opened 2019-12-16 11:34 UTC by GalateaTom

Closes #231

2019-12-16 15:22 UTC, WilfGala commented on README.md
> +    * generator_pool_size: **Help me explain with Wilf**
remove line 90 and replace with:

```
* number_of_create_child_processes: For each domain object, a parent create process manages the creation 
of domain object records and uses a pool of child processes to run batches of 'create jobs' in parallel. 
A 'create job' specifies a number of records to create as part of the total number specified in the 
'record_count' attribute for the domain object in question. A record in this case is a python dictionary, 
and created records are added to an intermediate queue to be received by the parent write process and written 
to file. 
* number_of_write_child_processes: For each domain object, a parent write process writes records to output 
files in batches, by defining 'write jobs' and passing these to a pool of write child processes to produce the 
output files by running the 'write jobs' in parallel. A 'write job' is a python dictionary containing the batch 
of records to be written to file, and the ID of the file to write them to.
* number_of_records_per_job: Both 'create jobs' and 'write jobs' refer to an action to be taken regarding a 
quantity of domain object records. This quantity is capped at this value across all jobs. This value is subject
to the constraint that it must be greater than 1, and less than or equal to the smallest max_objects_per_file
value across all domain objects in the config
```

2019-12-16 15:23 UTC, WilfGala commented on tests/utils/helper_methods.py
im sure this is fine but could you just clarify verbally why this is removed? does it relate to this issue or is it just general housekeeping? apologies if you have previously mentioned this and I've forgotten

2019-12-16 15:23 UTC, WilfGala requested changes
see comments

2019-12-17 11:47 UTC, GalateaTom commented on tests/utils/helper_methods.py
I removed get_configuration because it contains a hardcoded reference to config.json.  Therefore someone might get confused and think that they'd need to update this method if they're switching to a different config file.  get_configuration is only used in one of the Tampa PoC classes so I thought it simplest to remove it rather than actually fix the method

2019-12-17 11:52 UTC, GalateaTom commented
Changes made

2019-12-17 13:32 UTC, WilfGala approved these changes

2019-12-17 13:33 UTC, merged